"""versioning

Revision ID: cf0c6ef3900a
Revises: af056760889c
Create Date: 2023-02-11 12:46:04.787091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0c6ef3900a'
down_revision = 'af056760889c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('value', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_models_version'))
    )
    op.create_index(op.f('ix_models_version_end_transaction_id'), 'models_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_models_version_operation_type'), 'models_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_models_version_transaction_id'), 'models_version', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transaction_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('users')
    op.drop_index(op.f('ix_models_version_transaction_id'), table_name='models_version')
    op.drop_index(op.f('ix_models_version_operation_type'), table_name='models_version')
    op.drop_index(op.f('ix_models_version_end_transaction_id'), table_name='models_version')
    op.drop_table('models_version')
    # ### end Alembic commands ###
