"""support for states

Revision ID: 453595e2e992
Revises: af056760889c
Create Date: 2023-02-24 18:25:44.453343

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_fsm


# revision identifiers, used by Alembic.
revision = '453595e2e992'
down_revision = 'af056760889c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('state', sqlalchemy_fsm.sqltypes.FSMField(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'state')
    # ### end Alembic commands ###
